Конструкция для отлова ошибок.

Выглядит так:
```javascript
try{
	const x = 0
	x = 10
}catch(err){
	console.log(err)
}finally{
	console.log("Скрипт, который выполнится в любом случае")
}
```

Если в секции `try` будет выведена ошибка, то продолжение блока `try` завершается и происходит переход в блок `catch`. Он существует для отлова и обработки ошибки.

Блок `finally` будет выполнен не зависимо от исхода как `try`, так и `catch`.

*Если в `catch` будет выведена ошибка, то код Javascript останавливается*

[Javascript](Javascript)
